library(DBI)
library(dplyr)

## conexão com banco replica 
##test

con2 <- dbConnect(odbc::odbc(), "reproreplica")

dbGetQuery(con2,"
WITH CLI AS (SELECT CLICODIGO,CLINOMEFANT,CLIRAZSOCIAL,CLICNPJCPF,GCLCODIGO,CLIDTCAD,
REPLACE(REPLACE(REPLACE(CLICNPJCPF,'/',''),'-',''),'.','') CNPJ2,CLIPCDESCPRODU
FROM CLIEN),

SETOR AS (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA),

CID AS (SELECT CIDNOME,CIDCODIGO FROM CIDADE),

ENDE AS (SELECT ENDCLI.CLICODIGO,ENDTPRUA,ENDENDERECO,ENDNR,ENDCOMPLE,ENDBAIRRO,CIDNOME,ENDDDD1,ENDFONE1,ENDDDDCEL,ENDCELULAR,ZODESCRICAO FROM ENDCLI
INNER JOIN CLI ON ENDCLI.CLICODIGO=CLI.CLICODIGO
LEFT JOIN CID ON ENDCLI.CIDCODIGO=CID.CIDCODIGO
LEFT JOIN SETOR ON ENDCLI.ZOCODIGO=SETOR.ZOCODIGO
),

EMAIL AS (SELECT CLICODIGO,NETENDERECO FROM CLINET)

SELECT CLI.CLICODIGO,CLINOMEFANT,CLIRAZSOCIAL,GCLCODIGO,CLICNPJCPF CNPJ1,CNPJ2,ENDTPRUA
,ENDENDERECO,ENDNR,ENDCOMPLE,ENDBAIRRO,CIDNOME,ENDDDD1,ENDFONE1,ENDDDDCEL,ENDCELULAR,NETENDERECO, (ENDTPRUA
|| ENDENDERECO || ENDNR || ENDCOMPLE || ENDBAIRRO || CIDNOME || ENDDDD1 || ENDFONE1) FULLADDRESS, ZODESCRICAO,CLIPCDESCPRODU,CLIDTCAD
FROM CLI
LEFT JOIN ENDE ON CLI.CLICODIGO=ENDE.CLICODIGO
LEFT JOIN EMAIL ON CLI.CLICODIGO=EMAIL.CLICODIGO
") %>% View()
